# Generated by Django 4.2.1 on 2023-06-01 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntryProducts',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('totalQuantityByKilo', models.CharField(blank=True, max_length=1000, null=True)),
                ('totalQuantityByAmount', models.CharField(blank=True, max_length=1000, null=True)),
                ('total', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TotalProducts',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('totalEntriesByKilo', models.CharField(blank=True, max_length=1000, null=True)),
                ('totalEntriesByAmount', models.CharField(blank=True, max_length=1000, null=True)),
                ('totalOutgoingsByKilo', models.CharField(blank=True, max_length=1000, null=True)),
                ('totalOutgoingsByAmount', models.CharField(blank=True, max_length=1000, null=True)),
                ('totalReturnsByKilo', models.CharField(blank=True, max_length=1000, null=True)),
                ('totalReturnsByAmount', models.CharField(blank=True, max_length=1000, null=True)),
                ('totalProducts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='totalProducts', to='report.day')),
            ],
        ),
        migrations.CreateModel(
            name='SoldProducts',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('total', models.CharField(blank=True, max_length=1000, null=True)),
                ('totalQuantityByKilo', models.CharField(blank=True, max_length=1000, null=True)),
                ('totalQuantityByAmount', models.CharField(blank=True, max_length=1000, null=True)),
                ('soldProducts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soldProducts', to='report.totalproducts')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnProducts',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('totalQuantityByKilo', models.CharField(blank=True, max_length=1000, null=True)),
                ('totalQuantityByAmount', models.CharField(blank=True, max_length=1000, null=True)),
                ('total', models.CharField(blank=True, max_length=1000, null=True)),
                ('returns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='report.totalproducts')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_bar_code', models.CharField(blank=True, max_length=300, null=True)),
                ('product_name', models.CharField(blank=True, max_length=300, null=True)),
                ('product_size', models.CharField(blank=True, max_length=300, null=True)),
                ('product_price', models.CharField(blank=True, max_length=300, null=True)),
                ('product_quantity', models.CharField(blank=True, max_length=300, null=True)),
                ('product_total_price', models.CharField(blank=True, max_length=600, null=True)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='report.returnproducts')),
            ],
        ),
        migrations.CreateModel(
            name='ReportByProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_bar_code', models.CharField(blank=True, max_length=300, null=True)),
                ('product_name', models.CharField(blank=True, max_length=300, null=True)),
                ('product_price', models.CharField(blank=True, max_length=300, null=True)),
                ('product_quantity', models.CharField(blank=True, max_length=300, null=True)),
                ('product_size', models.CharField(blank=True, max_length=300, null=True)),
                ('product_total_price', models.CharField(blank=True, max_length=600, null=True)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='report.soldproducts')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_bar_code', models.CharField(blank=True, max_length=300, null=True)),
                ('product_name', models.CharField(blank=True, max_length=300, null=True)),
                ('product_price', models.CharField(blank=True, max_length=300, null=True)),
                ('product_size', models.CharField(blank=True, max_length=300, null=True)),
                ('product_quantity', models.CharField(blank=True, max_length=300, null=True)),
                ('product_total_price', models.CharField(blank=True, max_length=600, null=True)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='report.entryproducts')),
            ],
        ),
        migrations.AddField(
            model_name='entryproducts',
            name='entries',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='report.totalproducts'),
        ),
        migrations.AddField(
            model_name='day',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day', to='report.filial'),
        ),
    ]
