# Generated by Django 4.2.1 on 2023-06-26 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UploadAudioTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('audio', models.FileField(blank=True, null=True, upload_to='media')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_entry_price',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='reportbyproduct',
            name='product_entry_price',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='returnedproduct',
            name='product_entry_price',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='totalproducts',
            name='benefit',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('bar_code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('discription', models.CharField(blank=True, max_length=1000, null=True)),
                ('quantity_in_store', models.CharField(blank=True, default=0, max_length=1000, null=True)),
                ('quantity', models.CharField(blank=True, default=0, max_length=1000, null=True)),
                ('entry_price', models.CharField(blank=True, default=0, max_length=1000, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('is_important', models.BooleanField(default=False)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('old_price', models.CharField(blank=True, max_length=64, null=True)),
                ('discount', models.CharField(blank=True, max_length=10, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='report.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_link', models.CharField(blank=True, max_length=2000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('title', models.CharField(max_length=2500, null=True)),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='report.products')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_link', models.CharField(blank=True, max_length=2000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('title', models.CharField(max_length=2500, null=True)),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='report.category')),
            ],
        ),
    ]
